### PR TITLE
Allow access from all munin-server to the clients

### PR DESCRIPTION
**Pull request by kampfschlaefer**
With the extended multi-environment-monitoring, nodes can be monitored from several servers:
- non-'multi_environment_monitoring'-servers in the same environment
- 'multi_environment_monitoring'-servers in different environments

Allow them all to access the node.

### CODE REVIEW

**Comment by kampfschlaefer** [comment]
This could be argued about as this opens access for more servers then might be wanted. But if we have to distinguish between allowed environments for the clients and searched environments for the servers, it all becomes complicated...

**Comment by jesseadams** [comment]
@kampfschlaefer - This looks good. Can you please write a spec that proves it works as intended? I want to require this for all pull requests from now on.

Thanks!

**Comment by kampfschlaefer** [comment]
Hm, I did have a bit of controverse discussion with sethvargo about testing stuff like that. As that ruled out testing the search, the only usefull spec I can currently think of would be to stub a search-result for servers and check if these show up in the rendered munin-node.conf...

**Comment by jesseadams** [comment]
Thats exactly the kind of test I'd like to see :smile:

**Comment by jesseadams** [comment]
Closing in favor of #36

**Pull request closed without merging**
