### PR TITLE
Added node['munin']['server_list']

### PR DESCRIPTION
**Pull request by docwhat**
This allows finer grain control of the server list.  Including allowing for
the server to be outside this chef-server's control.

Use cases:
- Use chef-solo/zero to deploy testing VMs but wanting to report to
  different server(s).
- When migrating from another system (e.g. puppet) to Chef and the
  server(s) haven't been moved yet.

### CODE REVIEW

**Comment by jesseadams** [comment]
I like this idea @docwhat. We need to write a test for this use case and get this green.

**Comment by jesseadams** [comment]
Also, this will eventually be re-worked to function with #34

**Comment by docwhat** [comment]
@jesseadams Okay, some refactors and now some unit tests.  I didn't cover the code I didn't write, in part because I wasn't sure how to.

I suspect that that whole complicated bit of code that generates the `munin_server_ips` should be using an LWRP that can be skipped if someone wants to do something more interesting, instead of adding more `if`s.

**Comment by docwhat** [comment]
Yay! It passed!

**Comment by kampfschlaefer** [comment]
@jesseadams if in doubt, #34 will be reworked. The next weeks don't look like I could work on my pull-requests.

**Comment by jesseadams** [comment]
Nice work @docwhat

**Pull request merged**
