### PR TITLE
Fixed typo in README.md

### PR DESCRIPTION
**Pull request by ghost**
htpasswd does not emit anything about nagios when invoked with "munin" as an argument.

### CODE REVIEW

**Comment by jesseadams** [comment]
Hey @nutznboltz! Thank you for supporting the Opscode Cookbooks! Opscode's process has a couple prerequisites before they will merge your contribution. We need to ensure you've completed a Contributor License Agreement (CLA) and a ticket on their ticket tracker for the release workflow. Pull requests are optional, but should always include the ticket number that they're related to for cross-referencing. Please take a moment to review the below wiki page for the appropriate steps:
- http://wiki.opscode.com/display/chef/How+to+Contribute
- http://wiki.opscode.com/display/chef/Code+Review

**Comment by ghost** [comment]
I changed my mind.  There is no typo.

**Comment by jesseadams** [comment]
@nutznboltz Please consider closing this request if you no longer want it merged. Thanks!

**Comment by ghost** [comment]
I would, however the act might be viewed as a contribution which I could not perform due to having not signed the oaths etc.

**Pull request closed without merging**
